### DISCUSSION TITLE
Removing event Time and Check icons before event.

### DISCUSSION THREAD

**Discussion by Yezur** [MMRIZE/MMM-CalendarExt3#105] [Q&A] [answered]
Hi. Got everything up and running as wanted. Works great.
I want to do some styling but im not really familiair yet with customizing the css file.

Ideally I want to show the whole event name in the day (not sure if thats possible).
If thats not possible I want to remove the Time before an event and the "checkmark" icon.

Tried some things but keep breaking the config.

Any help would we really appreciated. 
Thanks

**Comment by eouia** [comment, marked as answer]
If there is not enough space, the whole event title would be truncated. title-wrapping is not supported (however possible with CSS modification, but not recommended. This module is not designed so for that intentionally.)

To remove icon and time, add these lines in your `custom.css`

```css
.CX3 .event .headline.useSymbol .symbol {
  display: none;
}

.CX3 .event:not(.fullday) .headline .time {
  display: none;
}

```
