### DISCUSSION TITLE
Custom.css entry not being followed

### DISCUSSION THREAD

**Discussion by swbreidert** [MMRIZE/MMM-CalendarExt3#130] [Q&A] [answered]
I attempted to hide the cw from displaying by adding a custom css entry for 

`.CX3 .cw {
display: none;
}`

Yet the cw still display. The debug console shows the Custom.css file was loaded yet this doesn't appear to be taking effect.

Is there something else I need to do?

**Comment by eouia** [comment, marked as answer]
There is some misdirection for this. It's my fault.
Try this.
```css
/* custom.css */
.CX3 .cellContainer .cell:nth-child(1) .cw {
  display: none;
}
```
