### DISCUSSION TITLE
changing standard colors

### DISCUSSION THREAD

**Discussion by epascua2** [MMRIZE/MMM-CalendarExt3#151] [Q&A] [answered]
How do I get the red and blue at the start and end of the week to just display white?

and how do I make it so all of my events text matches the color set in calendars module instead of just white?
![image](https://github.com/MMRIZE/MMM-CalendarExt3/assets/61392694/00bce020-526f-4e4a-aaf6-30b11b9d10f9)

I saw this discussion: 
https://github.com/MMRIZE/MMM-CalendarExt3/discussions/74 
but it did not help me out, i tried both and even renamed "mycustom" to one of my calendars and could not get it to change colors

**Comment by eouia** [comment, marked as answer]
```css
/* Append these into your css/custom.css */

.CX3 .weekend_2 {
  color: var(--defaultColor);
}

.CX3 .weekend_1 {
  color: var(--defaultColor);
}

.CX3 .event.singleday .title {
  color: var(--calendarColor);
}
```

<img width="1462" alt="image" src="https://github.com/MMRIZE/MMM-CalendarExt3/assets/1720610/29307185-b740-4bb8-9e8f-479f9a4800de">
