### DISCUSSION TITLE
font size를 변경하고 싶습니다.

### DISCUSSION THREAD

**Discussion by PaekHyun** [MMRIZE/MMM-CalendarExt3#164] [Q&A]
main.css 파일에서

:root {

--font-size-xsmall : 1rem;
--font-size-small : 1.25rem;
--font-size-medium : 1.7rem;

}

이런식으로 수정을 했는데.. (지금 코드를 안보고 써서 정확히는 모르겠는데 ..대충 쓴게 저런 코드 였습니다.  x.xx rem의 숫자를 키워서.)

calendarext3 / calendarex3timeline만 fontsize가 변하지 않습니다.
마찬자리로 custom.css 파일에 같은 코드를 넣어도 .. fontsize가 변하지 않는데
어떤 코드를 어떻게 수정해야 font size를 바꿀수 있을까요?

**Comment by PaekHyun** [comment]
아 ..찾았습니다. ;;
config 파일을 수정하면 글씨가 커지네요..^^;;;

**Comment by PaekHyun** [comment]
그런데 다른 글자는 다 커졌는데
월..표시만 그대로 작습니다.

월..을 어떻게 하면 크게 할 수 있을까요?

**Comment by eouia** [comment]
```css
.MMM-CalendarExt3 header {
  font-size: 2em;
  font-weight: bold;
  color: crimson;
  line-height: 1.1em;
}
```
![image](https://github.com/user-attachments/assets/8e4d2e33-d90b-4fee-8202-a5f1f03f4ba4)


모듈의 header 영역은 모듈의 css가 관리하는 곳이 아니라서 찾기 어려우셨을 거에요.
