### DISCUSSION TITLE
background transparency

### DISCUSSION THREAD

**Discussion by menthol89** [MMRIZE/MMM-CalendarExt3#172] [Q&A]
Hello

Whenever I try to change the transparency of the boxes, it only changes on one of the days, the rest stay the same.

`.CX3 {
  /* you CAN modify these values; but SHOULD NOT to remove */
  --celllinecolor: #333;
  --cellbgcolor: rgb(0 0 0 / 60%);
  --cellheaderheight: 25px;
  --cellfooterheight: 2px;
  --defaultcolor: #fff;
  --eventheight: calc(var(--fontsize) + 4px);
  --totalheight: calc(var(--eventheight) * var(--maxeventlines));
  --displayEndTime: none;
  --displayWeatherTemp: none;`

How do i make the rest of the days have the same transparency?

![billede_2024-10-06_210900676](https://github.com/user-attachments/assets/91ea497f-d924-4d6a-8311-8d7bf1bcb492)

**Comment by eouia** [comment]
Sorry for the late reply. I was on vacation.

Append these codes in your `custom.css`
```css
.CX3 .thisMonth {
  background-color: initial;
}

.CX3 .cell {
  background-color: initial;
}
```
