### DISCUSSION TITLE
Filter events by time

### DISCUSSION THREAD

**Discussion by gekberlin** [MMRIZE/MMM-CalendarExt3#175] [General]
Hi, 
we use the MMM-CalendarExt3Agenda to display our current week shedule. As it get quite noisy with all the work events it would be great, if we could filter the first two and the last event of the work calendars. Is this somehow possible? 

this is what claude 3.5 sonnet suggested, but its not working:

```
  {
          module: "MMM-CalendarExt3Agenda",
          position: "bottom_bar",
          config: {
            showMiniMonthCalendar: false,
            cellDateOptions: {day: 'numeric', weekday: "short"},
            calendarSet: ["Arbeit_first","Arbeit_second"],
            locale: "de",
            startDayIndex: 0,
            endDayIndex: 5,
            useIconify: true,
            eventFilter: (ev) => {
                  // Get all events for this calendar
                  const events = document.querySelectorAll(`[data-calendar-name="${ev.calendarName}"]`);
                  const index = Array.from(events).findIndex(e => 
                    e.getAttribute('data-event-id') === ev.id
                  );
                  
                  // Return true only for first two and last events
                  return index < 2 || index === events.length - 1;
                }
          }
        },
```

**Comment by eouia** [comment]
`the First and Second events` are not obvious. Anyway, I'll assume those are only for the `single` events, not for the `fullday` or `multiday` events.

Append these code into your `css/custom.css` (You don't need to use `eventFilter`)
```css
/* css/custom.css */
.CX3A .cell .single .event {
  display: none;
}

.CX3A .cell .single .event:nth-child(1),
.CX3A .cell .single .event:nth-child(2),
.CX3A .cell .single .event:last-child {
  display: block;
}
```


**Before**
<img width="399" alt="image" src="https://github.com/user-attachments/assets/50757f6a-225c-4861-b9a4-6ef7ac7bc4f0">

**After**
<img width="399" alt="image" src="https://github.com/user-attachments/assets/d19d6803-0caf-4c04-8834-4a3d15c3911c">
