### DISCUSSION TITLE
Enlarging the date in month view

### DISCUSSION THREAD

**Discussion by g00gl3s** [MMRIZE/MMM-CalendarExt3#205] [Q&A]
Hi,
newbie here. I have been playing around with the CSS and font size but unable to only make the date font size bigger. Is there a way to do this? Thanks.

**Comment by eouia** [comment]
Exactly what you mean? Do you have any sketches or more details?

**Reply by g00gl3s** [reply]
Hi,

Sorry for late reply. But what I am trying to do is make the date numbering in bigger font size. is this possible?

**Comment by eouia** [comment]
<img width="1631" alt="image" src="https://github.com/user-attachments/assets/c8d8e388-0dd1-46ea-89da-05b5ca573d3d" />

Append this into your `css/custom.css`
```css
/* css/custom.css */
.CX3 {
  --cellheaderheight: 40px;
}

.CX3 .cellHeader .cellDate {
  font-size: calc(var(--cellheaderheight) - 8px);
  line-height: 100%;
}
```
