### DISCUSSION TITLE
Changing the colour of weekends

### DISCUSSION THREAD

**Discussion by Whitling2k** [MMRIZE/MMM-CalendarExt3#50] [General]
How would I change the colour and font of the week and weekend days in the column headers using CSS?  i.e. "Saturday" and "Sunday" appear red and blue.  I would like every day the same font colour and size.

Awesome module by the way :-)

**Comment by eouia** [comment]
Those are defined in `MMM-CalendarExt3.css`.
https://github.com/MMRIZE/MMM-CalendarExt3/blob/9b97f69a2bccc1af8b9212a12bdec0ac6b21becf/MMM-CalendarExt3.css#L231-L237

But you should not edit that file directly.
Instead, you need to modify/add your overridden codes in `/css/custom.css`.

```css
.CX3 .weekday_0 { /* Sunday */
  color: inherit; /* Or what you want */
}

.CX3 .weekday_6 { /* Saturday */
  color: inherit; /* Or what you want */
}
```
