### DISCUSSION TITLE
Wrapping Text

### DISCUSSION THREAD

**Discussion by rcarnathan** [MMRIZE/MMM-CalendarExt3#9] [Q&A] [answered]
Has anyone figured out how to wrap the text of a calendar entry in either the weekly or monthly view?

**Comment by eouia** [comment]
It doesn’t support text wrapping.

**Comment by KristjanESPERANTO** [comment, marked as answer]
You should be able to enable text wrapping for calendar entries using custom CSS. Add this to your `custom.css`:

**Option 1: Allow unlimited text wrapping**
```css
/* Allow event titles to wrap to multiple lines */
.CX3 .event .headline .title {
  white-space: normal !important;
  overflow: visible !important;
  text-overflow: unset !important;
}
```

**Option 2: Limit to 2 lines with ellipsis (recommended)**
```css
/* Wrap event titles to maximum 2 lines, show ellipsis if longer */
.CX3 .event .headline .title {
  white-space: normal !important;
  overflow: hidden !important;
  display: -webkit-box !important;
  -webkit-line-clamp: 2 !important;
  -webkit-box-orient: vertical !important;
}
```

**Note:** If you have `useMarquee: true` enabled, you should disable it first or add:
```css
.CX3 .event .headline .title.marquee .marqueeText {
  animation: none !important;
}
```

This is intentionally not built into the module as text wrapping can cause layout issues with the grid system (events may overlap). Custom CSS gives you full control over the behavior.
