### DISCUSSION TITLE
Remove event start time and change color on CW

### DISCUSSION THREAD

**Discussion by m4nino** [MMRIZE/MMM-CalendarExt3#95] [Q&A] [answered]
Is it possible to remove the event start time and change the color of the week numbers (the orange)? 

![2023-09-28-211202_1920x1080_scrot_000](https://github.com/MMRIZE/MMM-CalendarExt3/assets/145551766/871c4c86-897f-467e-8940-36b89b220bf1)

**Comment by eouia** [comment, marked as answer]
In your `custom.css`

```css
.CX3 .event:not(.fullday) .headline .time {
  display: none;
}

.CX3 .cw {
  color: green;
}
```
