### ISSUE TITLE
Marquee not respecting custom.css

### ISSUE THREAD

**Issue by raisins77** [MMRIZE/MMM-CalendarExt3#158]
I was messing with the useMarquee option, and changing this css class:

```
.CX3 .event .headline .title.marquee .marqueeText {
  display: inline-block;
  white-space: nowrap;
  overflow: unset;
  animation: marquee calc(var(--marqueeLength) / 10) linear 2s infinite;
  min-width: 0;
}
```

Specifically, changing the duration of the animation property ``calc(var(--marqueeLength) / 10)``, does not appear to work in custom.css. Making the same change directly in MMM-CalendarExt3.css does work.

Changing the keyframes in custom.css does work.

**Comment by eouia** [comment]
Well, in my test, it works. Exactly what do you want to do with that changing? Please describe more details, such as AS-IS and TO-BE.

I added this rule in the `custom.css`.
```css
.CX3 .event .headline .title.marquee .marqueeText {
  text-decoration: underline; /* To check whether this rule applied */
  animation: marquee calc(var(--marqueeLength) / 100) linear 2s infinite; /* Changed from 10 to 100 */
}
```
This code makes the animation 10x faster. (and underlines)
![image](https://github.com/user-attachments/assets/f8f60d01-6440-496d-a886-92aba2236a36)
