### ISSUE TITLE
Unable to change cell background color

### ISSUE THREAD

**Issue by importantlyearnest** [MMRIZE/MMM-CalendarExt3#165]
Thanks for all the work on this project.

I can't seem to change the background color of the calendar at all. I have a slideshow of photos running fullscreen in the background at all times and want to ensure I can read the calendar's text regardless of the background photo.

I tried the MMM-CalendarExt3.css and altering the variable "--cellbgcolor" at the beginning, but no matter what I change there, the cells don't change color anywhere. Is there somewhere else that the cell's background color is pulled from that I'm missing?

**Comment by eouia** [comment]
```css
/* css/custom.css */
.CX3 .cell {
  background-color: darkslategray;
}

.CX3 .cell.thisMonth {
  background-color: darkolivegreen;
}

.CX3 .cell.today {
  background-color: rgba(255,255, 0, 0.5);
}

.CX3 .cell.month_9.date_10 {
  background-color: darkcyan;
}
```
![image](https://github.com/user-attachments/assets/2f3bca0c-73c5-4f3f-a4ec-c31333d6efdd)
