### ISSUE TITLE
Config to make calendar background more opaque?

### ISSUE THREAD

**Issue by tspinoso** [MMRIZE/MMM-CalendarExt3#214]
To make the background more opaque so the calendar stands out, i.e. more readable over a background image, which css config to change?

  --cellbgcolor: rgba(0, 0, 0, 0.2); 
or 
--defaultcolor: #FFF;

Or is there a better way to do this?  Thanks in advance for any help.

**Comment by KristjanESPERANTO** [comment]
@tspinoso Try this:

```css
/* Direct override for cell backgrounds */
.CX3 .cell {
  background-color: rgba(0, 0, 0, 0.4) !important;
}
```
