### ISSUE TITLE
useSymbol:false causes blue dot in front of events

### ISSUE THREAD

**Issue by sdetweil** [MMRIZE/MMM-CalendarExt3#35]
how do I get rid of the blue dot? 

had to comment out a bunch of css
```css
*.CX3 .event.singleday:not(.useSymbol)::before,
.CX3 .event.singleday.useSymbol .symbol.noSymbol::before {
  content: '⬤';
  color: var(--calendarColor);
  display: inline-block;
  padding-right: 2px;
  font-size: 75%;
}*/

.CX3 .event:not(.useSymbol) .symbol {
  display: none;
}
/*
.CX3 .event.useSymbol .symbol {
  display: inline-block;
  padding-right: 2px;
  font-size: 75%;
  align-self: center;
}

.CX3 .event.singleday.useSymbol .symbol {
  color: var(--calendarColor);
} */
```
